/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package collageify;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import collageify.collageify.controller.

class AppTest {
    @Test void sqlConnection() {
        assertTrue();

        
    }
}
