/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package collageify;

import collageify.collageify.controller.SpotifyCredentialsController;
import collageify.collageify.controller.SqlController;
import collageify.collageify.entities.SpotifyUserCredentials;
import collageify.web.exceptions.NoSPApiException;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import se.michaelthelin.spotify.exceptions.SpotifyWebApiException;

import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Time;

class AppTest {
    public SpotifyCredentialsController spotify;

    long millis;
    public SpotifyUserCredentials credentials;

    AppTest() throws SQLException, NoSPApiException, IOException, SpotifyWebApiException {
        millis = System.currentTimeMillis();
        credentials = new SpotifyUserCredentials(222, "abc", "def", 222, new Date(millis), new Time(millis));

    }
    public
    @Test void testIsTokenValidate(){
        assertTrue(credentials.isValid());
    }
    public
    @Test void testGrabKeysandValidate() throws SQLException, NoSPApiException, IOException, SpotifyWebApiException {
        spotify = new SpotifyCredentialsController();
        assertEquals(spotify.keysInSet(),3);
        assertTrue(spotify.areKeysValid());
    }
}
